### ISSUE TITLE
运行报错 ReferenceError: process is not defined

### ISSUE THREAD

**Issue by zss1004504439** [umbrella22/electron-vue-template#1]
![image](https://user-images.githubusercontent.com/24915880/62176516-6bf04f00-b374-11e9-8cf2-89221e9184e7.png)
npm run dev 出错
![image](https://user-images.githubusercontent.com/24915880/62176612-cbe6f580-b374-11e9-9152-2c45a0bd3e80.png)

**Comment by umbrella22** [comment]
请问您是npm安装的依赖吗，我这里是好的哦
![项目截图](https://user-images.githubusercontent.com/19886152/62187461-044dfa00-b39c-11e9-9d2c-0cc881d47206.png)

这个错误之前是有过，但是我在main.js中修复了呀，要不您试试重新下载一次？我刚刚跑了是可以的

**Comment by zss1004504439** [comment]
![image](https://user-images.githubusercontent.com/24915880/62194051-a2958c00-b3ab-11e9-8065-d3eda23ec387.png)
不行！
你node 版本多少

**Comment by zss1004504439** [comment]
> 请问您是npm安装的依赖吗，我这里是好的哦
> ![项目截图](https://user-images.githubusercontent.com/19886152/62187461-044dfa00-b39c-11e9-9d2c-0cc881d47206.png)
> 
> 这个错误之前是有过，但是我在main.js中修复了呀，要不您试试重新下载一次？我刚刚跑了是可以的

你的 node 版本 是多少

**Comment by umbrella22** [comment]
这个。。。您的node版本是蛮高的，不过讲道理应该是高版本兼容低版本才对，我的是10.15.3版本的
![Windows下的截图](https://user-images.githubusercontent.com/19886152/62222083-4f402f80-b3e5-11e9-8c13-809fc669eff9.png)
您看看

**Comment by zss1004504439** [comment]
已解决 切换node 版本即可，可能是相应的依赖包的版本问题？

**Comment by zss1004504439** [comment]
运行后 控制台报错 SidebarItem.vue 有问题
![image](https://user-images.githubusercontent.com/24915880/62257700-4a0cd000-b439-11e9-98f3-65d1b362233b.png)

**Comment by umbrella22** [comment]
哦好，我知道了你的报错应该是node-sass版本对nodejs的版本有挑剔，然后这个地方的话，您也是还需要花裤衩的vue-admin模板是吗？不需要的话可以直接剔除，写入您自己的代码的，如果也是需要的话，我稍后晚些会对这些地方的报错进行修正，您红框位置的报错是由于v-for和v-if在一起使用了，所以会有这个报错，不影响使用，和控制台的报错是无关的，您可以选择将路由表中的这里：
![解决控制台报错信息](https://user-images.githubusercontent.com/19886152/62269838-e3061000-b466-11e9-97d8-5925fc14996d.png)
由于一直没有时间将花裤衩的vue-admin完全挪过来，对您的开发造成了耽误感到抱歉，我会尽快完善这方面的进度，感谢您的使用
