### ISSUE TITLE
请问有没有遇到过，部分win7打开黑屏的问题

### ISSUE THREAD

**Issue by anzai1990** [umbrella22/electron-vue-template#10]

**Comment by umbrella22** [comment]
@anzai1990  您需要查看官网中，`gpu-process-crashed`处理方案，打开黑屏常见于电脑性能不够好或者是显卡设备出现问题，可以通过设置禁用显卡加速模式来处理黑屏问题

**Comment by anzai1990** [comment]
您的意思是不是说，出现这个问题，我们应该去解决电脑问题，而不是我们软件的问题？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sky"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 上午9:50
收件人: "umbrella22/electron-vue-template"<electron-vue-template@noreply.github.com&gt;; 
抄送: "laj"<332990433@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [umbrella22/electron-vue-template] 请问有没有遇到过，部分win7打开黑屏的问题 (#10)





 
@anzai1990  您需要查看官网中，gpu-process-crashed处理方案，打开黑屏常见于电脑性能不够好或者是显卡设备出现问题，可以通过设置禁用显卡加速模式来处理黑屏问题

**Comment by umbrella22** [comment]
@anzai1990 = =，electron可以通过`gpu-process-crashed`检测显卡是否进入了崩溃状态，如果是，则electron本身提供一个禁用显卡加速模式方法。不知道这么说您，是否理解？

**Comment by anzai1990** [comment]
理解了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sky"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 上午10:06
收件人: "umbrella22/electron-vue-template"<electron-vue-template@noreply.github.com&gt;; 
抄送: "laj"<332990433@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [umbrella22/electron-vue-template] 请问有没有遇到过，部分win7打开黑屏的问题 (#10)





 
@anzai1990 = =，electron可以通过gpu-process-crashed检测显卡是否进入了崩溃状态，如果是，则electron本身提供一个禁用显卡加速模式方法。不知道这么说您，是否理解？
