### ISSUE TITLE
webview如何配置preload

### ISSUE THREAD

**Issue by SENFJ** [umbrella22/electron-vue-template#106]
请问下，我在项目中使用到了webview，但是需要使用到preload.js，不知道怎么配置

**Comment by umbrella22** [comment]
你可以直接吧preload.js放到静态目录里然后类似静态文件一样的读取就可

**Comment by SENFJ** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已收到！

**Comment by SENFJ** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已收到！
