### ISSUE TITLE
集成旧vue2项目，运行时报警告，如何去除警告弹窗？或者如何不校验element-ui样式？

### ISSUE THREAD

**Issue by 350469960** [umbrella22/electron-vue-template#112]
<img width="1240" alt="image" src="https://github.com/umbrella22/electron-vue-template/assets/23090716/01ab3259-6441-41dc-98cd-5f06286406de">

<img width="1679" alt="image" src="https://github.com/umbrella22/electron-vue-template/assets/23090716/158fff0f-f9e5-43a5-b89c-48de401c1b86">

**Comment by umbrella22** [comment]
这样的情况你需要降级你的sass版本，这个应该是sass给出来的错误，sass和sass-loader都要降级并锁版本到你原来的老项目版本
