### ISSUE TITLE
build 后无法运行

### ISSUE THREAD

**Issue by tom-style** [umbrella22/electron-vue-template#124]
build 后报各种错误，npm pnpm yarn 打包后报的错还不一样，有些依赖并没有打包成功；

![image](https://github.com/umbrella22/electron-vue-template/assets/39619390/611db62f-0224-40de-b003-a50da94a70ed)

![image](https://github.com/umbrella22/electron-vue-template/assets/39619390/6eef22e3-dc44-42d5-b517-9456a5f11988)

**Comment by csdudu** [comment]
我打包成功后，也是运行electron-vue-admin Setup 0.0.1.exe无法成功：
![image](https://github.com/umbrella22/electron-vue-template/assets/5706088/33fcaf8b-ad57-47ed-b5c5-328f836a6c33)

**Comment by umbrella22** [comment]
@csdudu 你这个大概率是因为你已经运行了一个实例，并且是管理员权限，安装程序没有权限关闭它
@tom-style 你这个大概率是用了pnpm，包括你在vite分支我都怀疑你用的是pnpm去或者是yarn的另一个模式，他们都会干扰打包导致缺包
时间太久远了，我关闭issues了
