### ISSUE TITLE
萌新提问：怎么打包成web啊

### ISSUE THREAD

**Issue by maxleton-cyber** [umbrella22/electron-vue-template#131]
做完桌面应用程序，还想打包一个web版本的，看代码好像也有考虑打包成web的，但是不知道怎么修改，打包出来的都是exe安装包。在dist/web文件夹里也是空空的，能讲一下具体怎么修改才能打包web版本吗

**Comment by umbrella22** [comment]
web版本你就最好迁移到vite了，因为这里的webpack版本和electron耦合过深，会导致你修改繁重
