### ISSUE TITLE
mac:build打包报错Command failed: /Users/lixiaoshuai/Downloads/git/electron_hpyzs/node_modules/7zip-bin/mac/x64/7za a -bd -mx=7 -mtc=off -mm=Deflate -mcu /electron_hpyzs/build/*****.app

### ISSUE THREAD

**Issue by luosi416** [umbrella22/electron-vue-template#139]
yarn build:mac 报错：⨯ open /Users/lixiaoshuai/Downloads/git/electron_hpyzs/build/setup_mac_V1.0.2: no such file or directory  
  ⨯ Cannot cleanup: 

Error #1 --------------------------------------------------------------------------------
Error: Exit code: 2. Command failed: /Users/lixiaoshuai/Downloads/git/electron_hpyzs/node_modules/7zip-bin/mac/x64/7za a -bd -mx=7 -mtc=off -mm=Deflate -mcu /Users/lixiaoshuai/Downloads/git/electron_hpyzs/build/setup_mac_V1.0.2 ***.app

System ERROR:
E_INVALIDARG
请问这个怎么解决 谢谢

![截屏2024-06-19 11 31 56](https://github.com/umbrella22/electron-vue-template/assets/68273359/567e7029-4dff-4fb9-a540-13307f93ea4f)
![截屏2024-06-19 11 34 05](https://github.com/umbrella22/electron-vue-template/assets/68273359/2ef6f278-007a-40c4-be53-d5735ce449ce)

**Comment by umbrella22** [comment]
看起来是它没有那个权限去访问文件夹=-=，但是也没有更多信息了，虽然不建议sudo执行命令，不过这个时候也只能推荐是你试试sudo

**Comment by luosi416** [comment]
> 看起来是它没有那个权限去访问文件夹=-=，但是也没有更多信息了，虽然不建议sudo执行命令，不过这个时候也只能推荐是你试试sudo

sudo yarn run build:mac这样吗

**Comment by umbrella22** [comment]
是的，但是你需要判断你那边有没有还在运行的已打包实例
