### ISSUE TITLE
如何加载preload文件

### ISSUE THREAD

**Issue by mxy2316868975javascript** [umbrella22/electron-vue-template#144]
<img width="680" alt="image" src="https://github.com/user-attachments/assets/bd6aed80-ee2c-41ac-a093-30cc5aa9e89e">
<img width="614" alt="image" src="https://github.com/user-attachments/assets/5cf99d91-2bfd-43cb-8e91-4c73c9e4658a">

**Comment by umbrella22** [comment]
在新分支opt_rspack中有加载preload的示例
