### ISSUE TITLE
Attempting to call a function in a renderer window that has been closed or released.

### ISSUE THREAD

**Issue by zhouyangit** [umbrella22/electron-vue-template#22]
hi,你好，我在使用过程中，基本上只要修改了一下代码，控制台就会一直提示这个信息，不知道你有没有注意过，不清楚是electron的问题还是vue的问题

![Jietu20200912-142041](https://user-images.githubusercontent.com/13669516/92989006-69fb3800-f503-11ea-9b3a-e229d2615241.jpg)

**Comment by umbrella22** [comment]
well，你可能需要检查一下你是否将窗口关闭后又重新通过代码打开并执行了函数导致的~

**Comment by umbrella22** [comment]
还有您需要提供当前正在使用得分支~

**Comment by zhouyangit** [comment]
> 还有您需要提供当前正在使用得分支~

我用的是master分支，我看electron的issues里也有人提这个问题，[#22545](https://github.com/electron/electron/issues/22545)

**Comment by umbrella22** [comment]
`remote`基本在9以后就会收到警告了，建议使用ipc的形式叭。。这边也看不到您的代码，那就按官方说的来吧
