### ISSUE TITLE
请在代码上方加上仍然使用MinifyPlugin的原因，避免产生困扰

### ISSUE THREAD

**Issue by mtrucc** [umbrella22/electron-vue-template#23]
https://github.com/umbrella22/electron-vue-template/blob/f3d4fdd899c9e1d002e1f3c66aef3face774394c/.electron-vue/webpack.main.config.js#L9

https://www.webpackjs.com/plugins/babel-minify-webpack-plugin/

**Comment by umbrella22** [comment]
已去除
