### ISSUE TITLE
Electron 依赖升级建议

### ISSUE THREAD

**Issue by leohowl** [umbrella22/electron-vue-template#28]
直接升级依赖中的electron版本会有什么问题嘛？有没有升级的方法

**Comment by umbrella22** [comment]
一般在升级之前，建议先查看官方的更新日志，有没有废弃哪些api，一般跨超长版本的，不建议直接跳版本升级，一个是容易由于导致使用了废弃api而无法正常运行的情况，二是项目大了以后，改也很麻烦。

> 若真的要升级就可以运行第二第三分支内的 `yarn dep:upgrade`，然后选择即可，第一个分支的话就是删掉lock文件然后修改package.json的版本号了，不过不推荐这么做，一般用yarn就直接执行第二第三分支的这个命令就好

**Comment by leohowl** [comment]
好的，谢谢
