### ISSUE TITLE
自定义title有点小问题，以及功能的扩展问题！

### ISSUE THREAD

**Issue by ameibj** [umbrella22/electron-vue-template#3]
需求
1： 取消自带的工具菜单 frame ： false， 然后使用自定义的菜单， 右侧有缩小和放大和关闭，左侧需要暂时没有（这不是问题，变量可以控制）
2： 需要多窗口效果，类似于多显示器展示效果，引入了 electron-vue-windows 插件

**Comment by umbrella22** [comment]
@ameibj 
### 使用自定义头部您可以使用我的第二个分支
也就是[SynchronizedUpdates](https://github.com/umbrella22/electron-vue-template/tree/SynchronizedUpdates)，这里有您提到的自定义菜单栏，开启的话是在`src/renderer/config/index.js`中的`IsUseSysTitle`项；
> 但这里我没有做测试的是因为缺少mac设备
的问题，如果没有理解错的话，您提到的左侧需要是为了mac的红绿灯对吗？如果是的话，我会在今天或者明天着手修复一下自定义头部的问题。
### 如果您需要自定义状态栏的话
该组件在`src/renderer/components/title`中哦。
> 多窗口展示效果我会在这周看看，如果可以的话，也会更新在[SynchronizedUpdates](https://github.com/umbrella22/electron-vue-template/tree/SynchronizedUpdates)分支中，master分支很快将会归档到历史版本中了

**Comment by ameibj** [comment]
没有啊，我没关注适配问题。 现在是，我发现 用了 electron-vue-windows  新开的窗口 是透明的。我在找原因，我官方的 electron-vue 的脚手架项目是跑不起的。（之前也说过有可能是我升级了某个全局包导致，后来怎么都不知道是哪个包）

**Comment by ameibj** [comment]
加我个QQ 吧  576164240 ，方便及时聊天可以？

**Comment by ameibj** [comment]
![image](https://user-images.githubusercontent.com/16263441/66534338-7d11c500-eb48-11e9-9748-e7118e762bb8.png)
打包失败， 感觉升级后好多事啊。崩溃

**Comment by umbrella22** [comment]
@ameibj 
打包失败看上去是由于文件被占用导致的，建议打包时关闭您的所有编辑器，然后再执行打包操作，这种事情一般并不常见，您可以参考[苏南大叔的帖子](https://newsn.net/say/electron-vue-quick-fix.html)
