### ISSUE TITLE
npm run build:web 浏览器运行报错

### ISSUE THREAD

**Issue by starxg** [umbrella22/electron-vue-template#33]
`npm run build:web`

`+ 73 hidden modules
Child HtmlWebpackCompiler:
                          Asset      Size  Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  5.14 KiB       0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.55 KiB {0} [built]`

![image1](https://p.pstatp.com/origin/139300000129a4cd58cba)

![image2](https://p.pstatp.com/origin/137e80001e8711ca04408)

**Comment by umbrella22** [comment]
已修正

**Comment by starxg** [comment]
npm run build:web 失败。

npm:6.14.10
node:12.20.1

![image1](https://p.pstatp.com/origin/137b100029035fb5326e6)

**Comment by umbrella22** [comment]
你要自己解除任何和 **node模块** 有关的依赖哦，打包成web的时候是无法加载任何 **node模块** 。就比如图上的 **fs模** ,它存在于electron这个依赖中，所以你需要 **解除import electron** 哦
