### ISSUE TITLE
npm run build:web

### ISSUE THREAD

**Issue by whoishower** [umbrella22/electron-vue-template#36]
将应用程序打包成web后，Element-ui 表单无法渲染，控制台未报错。
![image](https://user-images.githubusercontent.com/39543641/111559850-3f4cad80-87cc-11eb-9653-f0f13ef5ddde.png)
但是相同源码打包为 npm run build:win64 打包成桌面程序是正常的

![image](https://user-images.githubusercontent.com/39543641/111559939-6e631f00-87cc-11eb-900d-40f7f8bc4c07.png)

**Comment by umbrella22** [comment]
done
