### ISSUE TITLE
启动报警 ExtensionLoadWarning

### ISSUE THREAD

**Issue by deanchou** [umbrella22/electron-vue-template#37]
分支 NoLayOut
 
启动后报

  (node:5040) ExtensionLoadWarning: Warnings loading extension at C:\Users\Dean\AppData\Roaming\Electron\extensions\nhdogjmejiglipccpnnnanhbledajbpd:
    Unrecognized manifest key 'browser_action'.
    Unrecognized manifest key 'update_url'.
    Permission 'contextMenus' is unknown or URL pattern is malformed.
    Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

  (Use `electron --trace-warnings ...` to show where the warning was created)

**Comment by umbrella22** [comment]
这是因为vue3的devTools的问题导致的，不影响使用

**Comment by deanchou** [comment]
收到 感谢回复
