### ISSUE TITLE
cross-env  多环境配置无效 

### ISSUE THREAD

**Issue by DreamPWJ** [umbrella22/electron-vue-template#41]
默认有development  production两个环境 但大部分应用还有test环境 或者其他环境  现在配置了test环境一直还是production环境  @umbrella22

**Comment by DreamPWJ** [comment]
建议添加一个test环境，大部分正规项目都需要

**Comment by umbrella22** [comment]
nolayout分支添加了TERGET_ENV，用于区分环境，和默认的development production并行，master稍后也会更新

**Comment by DreamPWJ** [comment]
主要是build打包的时候多环境   bbuild.js内都写死了
![image](https://user-images.githubusercontent.com/16730031/120273956-c4326800-c2e1-11eb-925a-6f7ac9efeee7.png)

**Comment by umbrella22** [comment]
不需要，已经传代码了，这里本来设置的时候，就是并行设置，并不是为了改动NODE_ENV来设置的，毕竟你可能会发布，开发板测试包，内测版测试包，稳定版测试包，这种。理想环境下对于代码而言应当只有开发和生产 一说，测试环境则按另一个标识来做类似服务端地址切换以及其他的操作

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/120279750-699d0a00-c2e9-11eb-93e3-3c04c3f5363f.png)
接口访问 给自动添加了前缀url路径  导致无法访问

**Comment by umbrella22** [comment]
= =你路径多了个“大哥。。。你都不看你请求的时候多拼接了个%22吗？

**Comment by DreamPWJ** [comment]
啥也没改，之前好使的，更新了你刚提交的代码而已，你可以测试一下@umbrella22

**Comment by umbrella22** [comment]
![image](https://user-images.githubusercontent.com/19886152/120286619-0adb8e80-c2f1-11eb-8a70-650db63c6825.png)
都说了你请求的连接多了一个 `"` 自己检查下代码好吗。。。。

**Comment by DreamPWJ** [comment]
代码示例上就有''

**Comment by DreamPWJ** [comment]
@umbrella22  有坑啊  build根本不行啊

**Comment by umbrella22** [comment]
麻烦看一下[更新日志](https://github.com/umbrella22/electron-vue-template/blob/master/README_ZH.md)，怎么去用这个

**Comment by umbrella22** [comment]
![image](https://user-images.githubusercontent.com/19886152/120318087-01165300-c312-11eb-9810-1a09e2f30d75.png)
= =对着更新日志看吧 @DreamPWJ 请求的那个问题我等等更新

**Comment by DreamPWJ** [comment]
@umbrella22  更新文档我都看了，为啥不测试build呢？一直很奇怪，只测试启动运行的话几乎不用修改 之前都好用

**Comment by umbrella22** [comment]
build打包有啥问题嘛。。。。主要是build那部分得你自己加上去啊= =，test环境目前要求的话，也不是很多，之前一直是想写，但是看需求量不高就一直搁置了而已

**Comment by DreamPWJ** [comment]
> build打包有啥问题嘛。。。。主要是build那部分得你自己加上去啊= =，test环境目前要求的话，也不是很多，之前一直是想写，但是看需求量不高就一直搁置了而已

build打包不管怎么设置TERGET_ENV 还是找prod.env环境

**Comment by umbrella22** [comment]
........ @DreamPWJ 
![image](https://user-images.githubusercontent.com/19886152/120413851-9c97da00-c38b-11eb-8904-1ea8494fa561.png)
![image](https://user-images.githubusercontent.com/19886152/120413913-b507f480-c38b-11eb-963c-052b97e52983.png)
![image](https://user-images.githubusercontent.com/19886152/120413957-c6e99780-c38b-11eb-9ebc-a8d32233e9f2.png)
![image](https://user-images.githubusercontent.com/19886152/120413987-d1a42c80-c38b-11eb-81d5-82a03707d8aa.png)
....... 唉......

**Comment by DreamPWJ** [comment]
不应该是 test: require('./test.env')？   我需要在test.env定义api地址啊

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/120415444-20eb5c80-c38e-11eb-9a8b-30770b0034ac.png)
zheli   这两个环境也不一致，不知道为啥有这样迷惑性设计

**Comment by umbrella22** [comment]
> ![image](https://user-images.githubusercontent.com/16730031/120415444-20eb5c80-c38e-11eb-9a8b-30770b0034ac.png)
> 这两个环境也不一致，不知道为啥有这样迷惑性设计， 用了一个月这个脚手架才发现多环境支持的不好，现在内测阶段一打包就要人工一直改env.js代码BASE_API地址，特别不方便， 没有electron-log现在只发现BASE_API地址不对

呐，既然有多环境了，那要是需要发布生产环境内测版，那你。。咋设置，如果要发布开发环境公测版，那又要咋设置。。所以干脆就并行两个了，想怎么玩就是你们的事情了。

-------------------------------------------------------------


> 不应该是 test: require('./test.env')？ 我需要在test.env定义api地址啊， 我们说的一直好像不是一个事情，能否把BASE_API地址打印出来？只打印环境没有意义啊，环境最重要的是找到对应的BASE_API地址啊 @umbrella22

然后是这里，这里是可以导入的，但是你需要设置一下axios的baseurl，由原`process.env.BASE_API` 修改为 -> `process.env.TERGET_ENV.BASE_API`这里我们假设你的test.env内容为
```js
module.exports = {
  NODE_ENV: '"test"',
  BASE_API: 'http://127.0.0.1:25565'
}
```
这样才可以取到，axios的配置文件在项目的`src\renderer\utils\request.js`.

**Comment by DreamPWJ** [comment]
process.env.TERGET_ENV.BASE_API  这个坑  感谢  已基本解决
