### ISSUE TITLE
请问有没有微信或者qq的交流群？谢谢啦

### ISSUE THREAD

**Issue by yy523697597** [umbrella22/electron-vue-template#5]
请问有没有微信或者qq的交流群？谢谢啦

**Comment by umbrella22** [comment]
@yy523697597  还没有成立群哦。。23333有啥问题直接在这里说吧~

**Comment by yy523697597** [comment]
准备用你的脚手架写一个项目，如果遇到问题，有个群的话会比较好交流呢，能给个qq或者微信不？

**Comment by umbrella22** [comment]
1035765115，备注一下来源就好；正常github，就好啦

**Comment by yy523697597** [comment]
使用 el-table 无法渲染内容，可以参考 https://blog.csdn.net/zzycsx/article/details/95977749 解决
