### ISSUE TITLE
nedb的使用问题

### ISSUE THREAD

**Issue by sharmine** [umbrella22/electron-vue-template#57]
请问，我在使用nedb的时候，因为main process&renderer process都需要操作同一个db,但是这样会造成两边读写不一致的现象。如何解决这个问题呢？（renderer process操作较多） 谢谢。

**Comment by umbrella22** [comment]
一般不建议双进程操作nedb，你可以换成一些信息传递用ipc

**Comment by sharmine** [comment]
> 一般不建议双进程操作nedb，你可以换成一些信息传递用ipc

目前我用ipc通信解决了，统一在主进程操作。
