### ISSUE TITLE
请求api接口Network不显示请求，只显示静态资源返回，console.log能打印出请求

### ISSUE THREAD

**Issue by anzai1990** [umbrella22/electron-vue-template#6]
![555](https://user-images.githubusercontent.com/26180858/71064544-4e4c4680-21aa-11ea-8265-915c6d95133f.png)

**Comment by anzai1990** [comment]
![图片_20191218151616](https://user-images.githubusercontent.com/26180858/71064255-9e76d900-21a9-11ea-81fa-f663d41c8585.png)
![图片_20191218151706](https://user-images.githubusercontent.com/26180858/71064261-a0d93300-21a9-11ea-96f6-2787cee8d271.png)

**Comment by umbrella22** [comment]
@anzai1990 
- 好的您的问题我刚刚看了
是由于我使用了最新版本的`axios`，在axios0.19版本中，**会直接去调用electron的net模块去访问网络，这样就造成了您无法在network中查看到请求过程，这一点和node服务器中使用axios很相似**， 
如果您需要能够在network中查看请求过程得话，这边建议您使用`npm uninstall axios -S`先卸载了当前的axios，然后使用`npm i axios@0.18.1 -S`来安装0.18.1版本的axios即可达到您想要的。

**Comment by anzai1990** [comment]
谢谢你的回复，还有个问题，如果我想升级到7或者8版本的Electron，应该如何操作呢？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sky"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 晚上6:30
收件人:&nbsp;"umbrella22/electron-vue-template"<electron-vue-template@noreply.github.com&gt;;
抄送:&nbsp;"laj"<332990433@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [umbrella22/electron-vue-template] 请求api接口Network不显示请求，只显示静态资源返回，console.log能打印出请求 (#6)




@anzai1990
  
好的您的问题我刚刚看了
 是由于我使用了最新版本的axios，在axios0.19版本中，会直接去调用electron的net模块去访问网络，这样就造成了您无法在network中查看到请求过程，这一点和node服务器中使用axios很相似，
 如果您需要能够在network中查看请求过程得话，这边建议您使用npm uninstall axios -S先卸载了当前的axios，然后使用npm i axios@0.18.1 -S来安装0.18.1版本的axios即可达到您想要的。

**Comment by umbrella22** [comment]
@anzai1990 
- 如果您在使用master版本得话，您可以先保留您的前端代码之后切换成 `SynchronizedUpdates` 分支即可享受最新稳定版的electron7，而`SynchronizedUpdates`分支中对主进程修改比较多，这是需要您注意的；然后`SynchronizedUpdates`分支日后在electron8发布稳定版之后将会提升至8版本，而master则会变成7版本并且保留6版本作为历史版不在维护发布在tags中。
- 如果您想自行更新electron版本，需要同时关注electron， electron-builder，electron-debug，electron-devtools-installer他们的版本号应当同时保持最新，但如果您保持了最新仍然出现故障问题，就只能参考github中他们的issue寻求解决办法了。

**Comment by anzai1990** [comment]
非常有帮助，谢谢你





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sky"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午5:41
收件人:&nbsp;"umbrella22/electron-vue-template"<electron-vue-template@noreply.github.com&gt;;
抄送:&nbsp;"laj"<332990433@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [umbrella22/electron-vue-template] 请求api接口Network不显示请求，只显示静态资源返回，console.log能打印出请求 (#6)




@anzai1990
  
如果您在使用master版本得话，您可以先保留您的前端代码之后切换成 SynchronizedUpdates 分支即可享受最新稳定版的electron7，而SynchronizedUpdates分支中对主进程修改比较多，这是需要您注意的；然后SynchronizedUpdates分支日后在electron8发布稳定版之后将会提升至8版本，而master则会变成7版本并且保留6版本作为历史版不在维护发布在tags中。
 
如果您想自行更新electron版本，需要同时关注electron， electron-builder，electron-debug，electron-devtools-installer他们的版本号应当同时保持最新，但如果您保持了最新仍然出现故障问题，就只能参考github中他们的issue寻求解决办法了。
