### ISSUE TITLE
大佬，在windows上的毛玻璃效果仅支持win10及以上版本吗？

### ISSUE THREAD

**Issue by daweiyong** [umbrella22/electron-vue-template#61]
大佬，在windows上的毛玻璃效果仅支持win10及以上版本吗？

**Comment by umbrella22** [comment]
@daweiyong 理论上是win8以上，但是为了确保体验的话，还是建议win10以上，因为不知道那个api到底有没有变化

**Comment by daweiyong** [comment]
> @daweiyong 理论上是win8以上，但是为了确保体验的话，还是建议win10以上，因为不知道那个api到底有没有变化

好的，谢谢大佬，明天上班试一试
