### ISSUE TITLE
win下的毛玻璃，建立动态链接库，连接建立后一直连接会影响性能吗

### ISSUE THREAD

**Issue by daweiyong** [umbrella22/electron-vue-template#62]
大佬可以给讲一下原理吗
1、如果是动态链接调用原生方法，并且连接不切断，对性能会有影响，有可能会把dll文件打包出来吗

**Comment by umbrella22** [comment]
## 关于毛玻璃需要的dll是否会被打包出来
 - 首先是不会的，这是肯定的，因为调用的dll是user32.dll，该dll是操作系统本身所携带的dll，只要操作系统本身带了这个dll就会去调用，并且在builder的配置中，我也没有设置将该dll一起打包，因为我也不知道这个dll所关联了什么其他的静态(动态)库。
## 关于性能损耗问题
 -  嗯，你是看到之前的vscode的[Vibrancy](https://eyhn.in/vscode-vibrancy/)拖动时候漂移才产生的疑惑嘛？但是他的那个是因为使用了错误的毛玻璃类型哦，并且作者在后续的更新已经修复了这个问题哦。
 - 并且操作系统本身的设置左侧的毛玻璃效果也是这个dll提供的，所以产生的性能开销几乎可以无视，但是在计算机性能本来就不佳的情况下(比如当前计算机甚至无法开启windows的全特效时)，还是建议关闭毛玻璃哦，那样确实会卡的。

## 关于类型说明
```js
const accent = new AccentPolicy();
// 颜色类型0-6
/**
 * ACCENT_DISABLED=0，禁用
 * ACCENT_ENABLE_GRADIENT=1，不透明，可以设置颜色
 * ACCENT_ENABLE_TRANSPARENT_GRADIENT=2，只透明，可以设置颜色
 * ACCENT_ENABLE_BLUR_BEHIND=3，毛玻璃，可以设置颜色
 * ACCENT_ENABLE_ACRYLIC_BLUR_BEHIND=4，如果要使用，除非你的窗口不可移动并无法拖动大小，否则将会出现，拖动之后窗口大小失控的问题.
 * ACCENT_ENABLE_HOST_BACKDROP=5， // 必须win10 1809以上才可以使用
 * ACCENT_INVALID_STATE= 6 非法6及其以上
 */
accent.AccentState = 3;
// 颜色值
// 255<<0|1<<8|2<<16|100<<24
// 其中255 1 2 100为rgba值，0 8 16 24是固定
accent.GradientColor = 0;
```

**Comment by daweiyong** [comment]
> ## 关于毛玻璃需要的dll是否会被打包出来
> * 首先是不会的，这是肯定的，因为调用的dll是user32.dll，该dll是操作系统本身所携带的dll，只要操作系统本身带了这个dll就会去调用，并且在builder的配置中，我也没有设置将该dll一起打包，因为我也不知道这个dll所关联了什么其他的静态(动态)库。
> 
> ## 关于性能损耗问题
> * 嗯，你是看到之前的vscode的[Vibrancy](https://eyhn.in/vscode-vibrancy/)拖动时候漂移才产生的疑惑嘛？这个是因为1903版本的更新，添加了亚克力毛玻璃效果的一个bug导致的，这个bug直到win11中才被修复。
> * 并且操作系统本身的设置左侧的毛玻璃效果也是这个dll提供的，所以产生的性能开销几乎可以无视，但是在计算机性能本来就不佳的情况下(比如当前计算机甚至无法开启windows的全特效时)，还是建议关闭毛玻璃哦，那样确实会卡的。
> 
> ## 关于类型说明
> ```js
> const accent = new AccentPolicy();
> // 颜色类型0-6
> /**
>  * ACCENT_DISABLED=0，禁用
>  * ACCENT_ENABLE_GRADIENT=1，不透明，可以设置颜色
>  * ACCENT_ENABLE_TRANSPARENT_GRADIENT=2，只透明，可以设置颜色
>  * ACCENT_ENABLE_BLUR_BEHIND=3，毛玻璃，可以设置颜色
>  * ACCENT_ENABLE_ACRYLIC_BLUR_BEHIND=4，如果要使用，除非你的窗口不可移动并无法拖动大小，否则将会出现，拖动之后窗口大小失控的问题.
>  * ACCENT_ENABLE_HOST_BACKDROP=5， // 必须win10 1809以上才可以使用
>  * ACCENT_INVALID_STATE= 6 非法6及其以上
>  */
> accent.AccentState = 3;
> // 颜色值
> // 255<<0|1<<8|2<<16|100<<24
> // 其中255 1 2 100为rgba值，0 8 16 24是固定
> accent.GradientColor = 0;
> ```

非常感谢，还有一个问题，如果毛玻璃开启不成功，如何捕捉到呢，因为开启毛玻璃就必须开启透明，这样的话，体验很不好。

**Comment by daweiyong** [comment]
![image](https://user-images.githubusercontent.com/20884900/129124214-3c483183-0b36-4936-b1a1-b10665a4c00b.png)
这样去判断好像是没有效果的

**Comment by umbrella22** [comment]
嗯，其实`SetWindowCompositionAttribute`函数是有返回值的，不需要你这样trycatch，例如
```js
const isSuccess = user32.SetWindowCompositionAttribute(handle.readInt32LE(), windowcompositon.ref());
```
如果成功了，isSuccess的值为1，失败了则是0，但通常情况下，在win10中，是生效的，只有在win10以下的版本可能会失败，因为win7的实现机制不太一样，后续的话，负责这部分的大佬会更新一下，兼容win7的部分。

**Comment by daweiyong** [comment]
> 嗯，其实`SetWindowCompositionAttribute`函数是有返回值的，不需要你这样trycatch，例如
> 
> ```js
> const isSuccess = user32.SetWindowCompositionAttribute(handle.readInt32LE(), windowcompositon.ref());
> ```
> 
> 如果成功了，isSuccess的值为1，失败了则是0，但通常情况下，在win10中，是生效的，只有在win10以下的版本可能会失败，因为win7的实现机制不太一样，后续的话，负责这部分的大佬会更新一下，兼容win7的部分。

谢谢大佬，没有找到合适的系统测试，但是相信肯定没有问题，谢谢

**Comment by umbrella22** [comment]
嗯嗯~因为这个api目前是微软的隐藏api，所以多多少少还是有些问题。。毕竟= =懂得都懂。。。按我issues就关闭了哈，如果还有什么问题可以再次开启

**Comment by daweiyong** [comment]
> 嗯嗯~因为这个api目前是微软的隐藏api，所以多多少少还是有些问题。。毕竟= =懂得都懂。。。按我issues就关闭了哈，如果还有什么问题可以再次开启

我加你微信和qq了奥，可以一起讨论下项目，希望可以通过奥.....
