### ISSUE TITLE
采用两个相同的工程，如何实现两个exe程序启动不会默认重叠为1个

### ISSUE THREAD

**Issue by Mr-HJM** [umbrella22/electron-vue-template#69]
相同的工程目录，copy了一份写另一套系统，但是打包完之后安装启动会默认成1个程序内，如图所示：
![T$JZ VBV JOQ1B8I1`@951B](https://user-images.githubusercontent.com/24948827/131793070-449dd1c3-f164-4da9-a16a-788d5fc893a0.jpg)

如何才能分开呢！ 
我的两个项目package.json为以下
![{%@%YWUG5PCUIP%$M7F9R_C](https://user-images.githubusercontent.com/24948827/131793117-4feccf82-366f-4dfe-9319-b2d5a1890ee0.png)
![_H2 _`0_MK% 4L)%2MMO(H](https://user-images.githubusercontent.com/24948827/131793143-c19c7cb0-ad3e-45f3-a143-a0b2a26e0e7d.png)

**Comment by Mr-HJM** [comment]
而且安装的时候安装完第一个exe程序，再安装第二个程序的时候会提示是否重新安装和升级
![image](https://user-images.githubusercontent.com/24948827/131799962-5b6d486a-fc0e-43b7-864b-0572002a3b65.png)

**Comment by umbrella22** [comment]
确保两个应用中`package.json->build->appId`不同即可

**Comment by Mr-HJM** [comment]
> 确保两个应用中`package.json->build->appId`不同即可

已解决！
