### ISSUE TITLE
electron-updater 可以实现热更新吗

### ISSUE THREAD

**Issue by Mr-HJM** [umbrella22/electron-vue-template#70]
想通过electron-updater然后实现免安装的热更新，现在autoUpdater更新都是下载完安装后还需要手动重新安装。有没有其他办法实现热更新免安装！

**Comment by umbrella22** [comment]
= =updater做不到热更新，如果你要热更新那么你就需要解包，然后自行下载并替换这个功能在vite仓库是有的，不过代价就是需要解包
