### ISSUE TITLE
element-ui组件el-slider部分功能无法使用使用

### ISSUE THREAD

**Issue by shubifeng** [umbrella22/electron-vue-template#73]
![图片](https://user-images.githubusercontent.com/6796352/140606434-33e2859b-aabf-42ed-a4cc-de1a5802ca23.png)

![图片](https://user-images.githubusercontent.com/6796352/140606450-7fa4fcd4-37aa-4b3c-b579-cb2c8ce3907a.png)

**Comment by umbrella22** [comment]
![image](https://user-images.githubusercontent.com/19886152/140606622-d031453e-e726-4f90-badd-ad2cb2a7fe8e.png)
**说起来，这里的报错不是告诉你，min和max必须为数字吗？**
```html
<el-slider v-model="value2" :step="10" show-stops :min="0" :max="50000"> </el-slider>
```
这样就不会报错了啊，而且这个报错是不会影响使用，告诉你的是类型错误。

建议是，好好阅读一下文档
![image](https://user-images.githubusercontent.com/19886152/140606741-0d9c098c-86e2-4fa6-ab4d-acac31ad92f1.png)

**Comment by shubifeng** [comment]
是element-ui的bug，这个组件跟其他页面元素嵌套在一起混用引发的。多谢。。
