### ISSUE TITLE
nedb需要自己安装吧

### ISSUE THREAD

**Issue by shubifeng** [umbrella22/electron-vue-template#74]
![图片](https://user-images.githubusercontent.com/6796352/142755083-13ad4a3e-484c-480d-9050-861145a93bb4.png)
这个还需要npm install吧，兄弟有咩有连接示例

**Comment by umbrella22** [comment]
nedb已经移除了，文档昨天更新了，请自行安装~或转使用sqlite3 or better sqlite3
