### ISSUE TITLE
自动跳回到登陆界面

### ISSUE THREAD

**Issue by goodZhaoliu** [umbrella22/electron-vue-template#8]
程序第一次启动时，点击登陆，跳转到其他界面，过一会后，会自动跳回到登陆界面！

**Comment by umbrella22** [comment]
emm。。。这个bug是已知的，因为登录那里是假的数据登录，存储的位置都是在内存中，只要你修改了渲染内存中的代码就会清空掉原有的登录信息，我在想是否要关掉这部分的路由拦截，因为这是一个例子，当你接入了登录接口并且将信息存储到localStorage之后，就不会出现这种情况了

**Comment by goodZhaoliu** [comment]
感谢，已经把登陆界面去除了，目前在用你这个框架做一个自用小工具，试试水，哈哈哈！

**Comment by umbrella22** [comment]
嗯没事能帮到你就好
