### ISSUE TITLE
Some speace in code

### ISSUE THREAD

**Issue by mtrucc** [umbrella22/electron-vue-template#82]
https://github.com/umbrella22/electron-vue-template/blob/9216322f496f2bb97c3873d0e9d0faefdf763c94/src/main/services/checkupdate.js#L9

<img width="583" alt="image" src="https://user-images.githubusercontent.com/16724665/155648838-3c87c6dc-b7f1-46f0-9740-898a2db66292.png">

This is a small and insignificant mistake

You can install **[Eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)** to format code.
Or Install **[Trailing Spaces](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces)**

Solve this problem and your program gets better and better!

**Comment by umbrella22** [comment]
Of course, thank you for your reminder. This part will be improved in the near future
