### ISSUE TITLE
index.ejs引用压缩过的js文件

### ISSUE THREAD

**Issue by DLTech21** [umbrella22/electron-vue-template#86]
在常规的electron demo中可以通过index.html里面引用script是ok的，但在此项目的index.ejs是如何引用，js文件是放到哪个目录下呢？谢谢

**Comment by umbrella22** [comment]
= =很抱歉才看到，一样的，ejs里有说static目录位置，直接字符串模板拼接就好了

**Comment by DLTech21** [comment]
嗯，那如果是引用webassembly呢，emscripton打包出来有一个js和wasm文件，那这个会出现js是引用了，但是js里面引用wasm文件就会报路径错误，这个能解决吗？
![image](https://user-images.githubusercontent.com/2238211/164353233-a2d8ac2b-9f6a-40a3-9a63-6a173e705c09.png)

**Comment by umbrella22** [comment]
emm这看起来是wasm不能被asar化，您可以选择像使用dll那样，按文档中的方法启用[__dll](https://zh-sky.gitee.io/electron-vue-template-doc/Overview/#%E5%85%A8%E5%B1%80%E6%96%87%E4%BB%B6%E5%A4%B9)，通过js注入的形式去挂载也可以

**Comment by DLTech21** [comment]
通过路径解决了，由于这个js可能被认为是在asar下，导致js里面的locate File依然去到这个路径找wasm文件，这时候可以通过改依赖js里面的locateFile的路径即可
