### ISSUE TITLE
打包后 iframe页面空白

### ISSUE THREAD

**Issue by smokedrinking** [umbrella22/electron-vue-template#89]
在开发模式下可以正常正常显示
<img width="973" alt="image" src="https://user-images.githubusercontent.com/52225525/165913992-86d13050-f861-4777-82a7-7534cd0bf07b.png">

我需要怎么做

**Comment by smokedrinking** [comment]
是打包后找不到页面地址吗

**Comment by sky-rainy** [comment]
> 是打包后找不到页面地址吗

1.看下路径
2.看下pdf是否打进包里了

**Comment by smokedrinking** [comment]
> > 是打包后找不到页面地址吗
> 
> 1.看下路径 2.看下pdf是否打进包里了

<img width="497" alt="image" src="https://user-images.githubusercontent.com/52225525/165916531-252bb2c8-724a-4095-bb96-23bcbd3784a9.png">
确定了空白是因为找不到静态的html pdf是在页面里面加载的 这是打包后的图片

**Comment by smokedrinking** [comment]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/52225525/165936131-699dfe9f-d094-4641-ac81-66ce6b30b39b.png">
感谢回答！
