### ISSUE TITLE
打包时发生错误

### ISSUE THREAD

**Issue by serfend** [umbrella22/electron-vue-template#9]
PS C:\Users\huawei\Documents\github\electron-vue-template> npm run build:win64

> electron-vue-admin@0.0.1 build:win64 C:\Users\huawei\Documents\github\electron-vue-template
> node .electron-vue/build.js && electron-builder --win  --x64

 ___              __        _                    __                       ___       __    
/\_ \       __   /\ \__   /\ \   ____           /\ \       __  __   __   /\_ \     /\ \   
\//\ \    / ,.`\ \ \ ,_\  \ \/  / ,__\  _______ \ \ \____ /\ \/\ \ /\_\  \//\ \    \_\ \  
  \_\ \_ /\  __/  \ \ \/   \/  /\__, `\/\______\ \ \  ,. \\ \ \_\ \\/\ \   \_\ \_ /\ ,. \ 
  /\____\\ \____\  \ \ \_      \/\____/\/______/  \ \____/ \ \____/ \ \ \  /\____\\ \____\
  \/____/ \/____/   \ \__\      \/___/             \/___/   \/___/   \/_/  \/____/ \/___ /
                     \/__/

  | building main process
  | building renderer process

   ERROR  failed to build renderer process

    Hash: 826c7218271b5ab0b1b3
    Version: webpack 4.41.6
    Time: 19850ms
    Built at: 2020-02-27 19:27:46
                              Asset       Size  Chunks  Chunk Names
                               0.js   10.9 KiB       0
                               2.js   13.1 KiB       2
                               3.js   10.5 KiB       3
                               4.js   5.63 KiB       4
                               5.js  320 bytes       5
     fonts/element-icons--fonts.ttf   54.6 KiB
    fonts/element-icons--fonts.woff   27.5 KiB
           imgs/404--404_images.png   95.8 KiB
              imgs/logo--assets.png   60.4 KiB
              imgs/user--assets.png   17.7 KiB
    Entrypoint renderer =
      [2] ./node_modules/vue/dist/vue.esm.js 319 KiB {1} [built]
      [3] ./node_modules/vue-loader/lib/runtime/componentNormalizer.js 2.63 KiB {1} [built]
      [5] ./node_modules/vue-style-loader/lib/addStylesClient.js + 1 modules 6.71 KiB {1} [built]
          | ./node_modules/vue-style-loader/lib/addStylesClient.js 6.09 KiB [built]
          | ./node_modules/vue-style-loader/lib/listToStyles.js 637 bytes [built]
      [7] ./node_modules/element-ui/lib/utils/util.js 7.15 KiB {1} [built]
      [8] ./node_modules/element-ui/lib/utils/dom.js 6.67 KiB {1} [built]
     [11] ./node_modules/element-ui/lib/mixins/emitter.js 1010 bytes {1} [built]
     [14] external "vuex" 42 bytes {1} [built]
     [15] ./node_modules/element-ui/lib/element-ui.common.js 1.1 MiB {1} [built]
     [26] external "nprogress" 42 bytes {1} [built]
     [27] ./node_modules/element-ui/lib/locale/index.js 1.68 KiB {1} [built]
     [28] ./node_modules/element-ui/lib/utils/vue-popper.js 5.79 KiB {1} [built]
    [182] ./node_modules/element-ui/lib/theme-chalk/index.css 436 bytes {1} [built]
    [207] ./src/renderer/styles/index.scss 509 bytes {1} [built]
    [209] external "vue-electron" 42 bytes {1} [built]
    [210] ./src/renderer/main.js + 71 modules 39.9 KiB {1} [built]
          | ./src/renderer/main.js 604 bytes [built]
          | ./src/renderer/App.vue 510 bytes [built]
          | ./src/renderer/store/index.js 203 bytes [built]
          | ./src/renderer/router/index.js 251 bytes [built]
          | ./src/renderer/api/operationalData.js 1.34 KiB [built]
          | ./src/renderer/permission.js 1020 bytes [built]
          | ./src/renderer/error.js 590 bytes [built]
          | ./src/renderer/icons/index.js 285 bytes [built]
          | ./src/renderer/App.vue?vue&type=template&id=0ddf392e& 201 bytes [built]
          | ./src/renderer/App.vue?vue&type=script&lang=js& 344 bytes [built]
          | ./src/renderer/store/getters.js 450 bytes [built]
          | ./src/renderer/router/constantRouterMap.js 1.28 KiB [built]
          | ./src/renderer/utils/db.js 208 bytes [built]
          | ./src/renderer/components/SvgIcon/index.vue 566 bytes [built]
          | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=template&id=0ddf392e& 237 bytes [built]
          |     + 57 hidden modules
        + 227 hidden modules

    ERROR in chunk renderer [entry]
    renderer.js
    C:\Users\huawei\Documents\github\electron-vue-template\node_modules\babel-loader\lib\index.js!C:\Users\huawei\Documents\github\electron-vue-template\src\renderer\main.js 35f0d045592d778e3b7c34f6556cfa62
    Unexpected token (12:48)
    |
    |
    | if (!Object({"NODE_ENV":"production","BASE_API":}).IS_WEB) __WEBPACK_MODULE_REFERENCE__0_64656661756c74__.use(__webpack_require__(209));  
    | __WEBPACK_MODULE_REFERENCE__0_64656661756c74__.use(__WEBPACK_MODULE_REFERENCE__84_64656661756c74__);
    | __WEBPACK_MODULE_REFERENCE__0_64656661756c74__.prototype.$db = __WEBPACK_MODULE_REFERENCE__83_64656661756c74__;
    Child html-webpack-plugin for "index.html":
             Asset     Size  Chunks  Chunk Names
        index.html  533 KiB       0
        Entrypoint undefined = index.html
        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.21 KiB {0} [built]
        [1] ./node_modules/lodash/lodash.js 528 KiB {0} [built]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vue-admin@0.0.1 build:win64: `node .electron-vue/build.js && electron-builder --win  --x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-vue-admin@0.0.1 build:win64 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huawei\AppData\Roaming\npm-cache\_logs\2020-02-27T11_27_47_081Z-debug.log

**Comment by umbrella22** [comment]
错误信息上来看是由于您渲染进程内代码错误，请检查您的代码后重新打包。

**Comment by serfend** [comment]
所有的都是按照文档使用默认的官方样例直接运行的，没有修改任何代码。建议检查兼容性

**Comment by umbrella22** [comment]
![打包成功](https://user-images.githubusercontent.com/19886152/75526671-29e3d480-5a4d-11ea-847b-3d8cf474e9b4.png)
![QQ截图20200228171157](https://user-images.githubusercontent.com/19886152/75526831-73342400-5a4d-11ea-9506-9b2c652a65b5.png)
**如图，自检无异常。**

**Comment by serfend** [comment]
好吧，感谢作者。
