### ISSUE TITLE
Mac m1打包win的测试

### ISSUE THREAD

**Issue by bulolo** [umbrella22/electron-vue-template#92]
一般建议你看一眼electron官网，支持linux但是不能打包apk

_Originally posted by @umbrella22 in https://github.com/umbrella22/electron-vue-template/issues/90#issuecomment-1127715661_

<img width="799" alt="image" src="https://user-images.githubusercontent.com/10026498/168777645-bafa511a-ff77-4ea5-8841-9f3e1100caf4.png">

我指的是这个脚手架的打包apk能跑安卓吗，但是您又说不能打包apk，而electron-builder说可以，确实搞晕了

**Comment by bulolo** [comment]
同时反馈一下，
我把项目原封不动在mac打包build:32,然后在win10上实际是跑步起来了

**Comment by umbrella22** [comment]
━Σ(ﾟДﾟ|||)━，太久没看builder的文档了（脸疼，但是electron官方是不支持打包成Android的，所以我想此处的apk应该不是指Android的安装包，等等我去看看builder的源码

**Comment by umbrella22** [comment]
![image](https://user-images.githubusercontent.com/19886152/168781082-ec8a1e8b-8dce-4676-a305-74b02b058b05.png)
![image](https://user-images.githubusercontent.com/19886152/168781112-9c353a47-e5c6-4438-9e55-64f9fe6e586f.png)
我这里倒是情绪稳定；您打包的时候控制台输出的是这样的吗？
![image](https://user-images.githubusercontent.com/19886152/168781291-8c976c0a-3040-4e94-b8bd-3e23676b3438.png)

**Comment by bulolo** [comment]
> ![image](https://user-images.githubusercontent.com/19886152/168781082-ec8a1e8b-8dce-4676-a305-74b02b058b05.png)
> 
> ![image](https://user-images.githubusercontent.com/19886152/168781586-9a2b0561-1166-4177-b657-6deb38004400.png)
> 
> 我这里倒是情绪稳定；您打包的时候控制台输出的是这样的吗？
> 
> ![image](https://user-images.githubusercontent.com/19886152/168781291-8c976c0a-3040-4e94-b8bd-3e23676b3438.png)
> 
> 顺带值得一提的是，您的mac是m1芯片还是？如果是m1芯片也许，是和这个有关系


我是m1，有可能就是这个原因

**Comment by umbrella22** [comment]
> > ![image](https://user-images.githubusercontent.com/19886152/168781082-ec8a1e8b-8dce-4676-a305-74b02b058b05.png)
> > ![image](https://user-images.githubusercontent.com/19886152/168781586-9a2b0561-1166-4177-b657-6deb38004400.png)
> > 我这里倒是情绪稳定；您打包的时候控制台输出的是这样的吗？
> > ![image](https://user-images.githubusercontent.com/19886152/168781291-8c976c0a-3040-4e94-b8bd-3e23676b3438.png)
> > 顺带值得一提的是，您的mac是m1芯片还是？如果是m1芯片也许，是和这个有关系
> 
> 我是m1，有可能就是这个原因

您可以尝试打包64位，我测试了下64的包是可以的，如果32包不行的话，也许是apple做了什么

**Comment by bulolo** [comment]
## 非m1-win10 测试楼

TODO：

**Comment by bulolo** [comment]
## m1-win10 测试楼

TODO：

**Comment by bulolo** [comment]
@umbrella22 
今天实际测试了m1的win32和64,也是均无法打开。因家里不是m1，明天我在公司再重新测下m1的，需要复现沟通加下微信：bulolo

**Comment by umbrella22** [comment]
从普遍理性来说，我觉得您应该先试一试官方的[demo](https://github.com/electron/fiddle/tree/v0.28.1)，如果electron-forge 同样无法正常工作，我想，您可能需要检查一下您的环境了

**Comment by bulolo** [comment]
> 

已经更更新m1的测试结果，也是不行。更新在上面m1-win10测试楼

官方的[demo](https://github.com/electron/fiddle/tree/v0.28.1)这个是指我要打包然后运行在win10？我看了下打包命令，不是很清楚怎么打包。还是说
<img width="759" alt="image" src="https://user-images.githubusercontent.com/10026498/168934122-31792d17-d1a8-46de-8f0a-b79586589b6c.png">
下载这个运行包试试就可以了？

**Comment by bulolo** [comment]
@umbrella22 再更新一个重要信息
build:win64 打包出来的安装起是可以安装后启动
但是打包出来的文件夹里面不可运行

<img width="578" alt="image" src="https://user-images.githubusercontent.com/10026498/168945923-c0b20103-c3a8-4226-9231-c25b1d96990b.png">

**Comment by umbrella22** [comment]
> @umbrella22 再更新一个重要信息 build:win64 打包出来的安装器是可以安装后启动 但是打包出来的文件夹里面不可运行
> 
> <img alt="image" width="578" src="https://user-images.githubusercontent.com/10026498/168945923-c0b20103-c3a8-4226-9231-c25b1d96990b.png">

那就很奇怪了，除非是你的**windows设置了无法运行绿色版软件或者是安全软件拦截**，否则安装包仅仅只是一个压缩解压缩过程以及写入注册表该软件已安装

**Comment by umbrella22** [comment]
抱歉时隔这么久回复，我仍然没有复现出来，唯一可以得知的，大概率是express导致的问题，但是你可以将其删除以后再测试~~
