### ISSUE TITLE
打包后dll路径不对问题（126）

### ISSUE THREAD

**Issue by dev-kain** [umbrella22/electron-vue-template#93]
### 你好，首先感谢大佬的这个项目，给我提供了很大的便利。
 @umbrella22 

### 问题：

1. 我最近有一个调用dll的需求，我跟着文档内一步一步走了，并且确认了好几遍，但是打包之后，一打开就报126（路径不对的）问题，`yarn dev` 运行是没问题的。

### 新增
1. 在static同级目录下（也就是项目根目录下）创建了dll_lib目录，存放dll
3. 新建了dll_lib_test.js文件，用以测试dll，放置在main目录下，代码如下

```
// 主进程中调用
import ffi from "ffi-napi";

console.log("dll test starting...");
const dll = ffi.Library(`${process.env.libPath}/dpet-windows-dll.dll`, {
  // 这里是c++中对js暴漏的方法，举个例子：
  // 这里是c++中暴漏了一个名为test的方法，它接受两个int类型，返回结果也是int类型
  add: ["int", ["int", "int"]],
});
// 假设该c++中的方法是相加并抛出结果，那么这里得出的结果应该是4
console.log(dll.add(1, 2));
process.exit(0);
```

### 改动
![origin_img_v2_e0b391df-cfb8-4285-be45-6b8a180b943g](https://user-images.githubusercontent.com/44948284/176119811-3a560f04-70b4-4a66-b01c-69ca60c2b21c.jpg)
```js
--- a/config/index.js
+++ b/config/index.js
@@ -17,7 +17,7 @@ module.exports = {
   production: require('./prod.env'),
   UseStartupChart: true,
   IsUseSysTitle: true,
-  DllFolder: '',
+  DllFolder: 'dll_lib', 
   BuiltInServerPort: 25565,
   UseJsx: true
 }


--- a/package.json
+++ b/package.json
@@ -21,7 +21,9 @@
   },
   "build": {
     "asar": false,
-    "extraFiles": [],
+    "extraFiles": [
+      "dll_lib"
+    ],
     "publish": [
       {
         "provider": "generic",
@@ -67,6 +69,7 @@
     "axios": "^0.27.2",
     "electron-updater": "^5.0.1",
     "express": "4.17.3",
+    "ffi-napi": "^4.0.3",
     "fs-extra": "^10.1.0"
   },
   "devDependencies": {
@@ -107,7 +110,7 @@
     "css-loader": "^6.7.1",
     "date-fns": "^2.28.0",
     "del": "^6.1.1",
-    "electron": "17.2.0",
+    "electron": "13.5.2",
     "electron-builder": "^23.0.3",
     "electron-devtools-installer": "^3.2.0",
     "element-ui": "^2.15.9",


--- a/src/main/index.js
+++ b/src/main/index.js
@@ -1,6 +1,7 @@
 'use strict'

 import { app } from 'electron'
+import {} from "./dll_lib_test"
```
### 最后
各位看官有什么想法也可以提，也许你随口一提就解决了困扰我的问题。

**Comment by sky-rainy** [comment]
config\index.js

**Comment by sky-rainy** [comment]
config\index.js
里的`DllFolder` 配置你的dll文件夹名称 存放DLL
通过 process.env.libPath  找你的dll
文档里有写你看下

**Comment by umbrella22** [comment]
有没有一种可能，126说的是你的dll的dll没有找到，而不是你的dll没有找到

**Comment by dev-kain** [comment]
>

**Comment by dev-kain** [comment]
> `config\index.js` 里的`DllFolder` 配置你的dll文件夹名称 存放DLL 通过 `process.env.libPath` 找你的dll 确定下 `process.env.libPath` 还有就是dll前边是反斜杠 `\\xxx.dll`

还有这么一说~ 好，我试试

**Comment by dev-kain** [comment]
> 有没有一种可能，126说的是你的dll的dll没有找到，而不是你的dll没有找到

蛤~ 那这有点离谱了吧，我不太懂c++

**Comment by dev-kain** [comment]
> `config\index.js` 里的`DllFolder` 配置你的dll文件夹名称 存放DLL 通过 `process.env.libPath` 找你的dll 确定下 `process.env.libPath` 还有就是dll前边是反斜杠 `\\xxx.dll`

刚试了一下，还是一样的报错

**Comment by umbrella22** [comment]
是，dll之间会相互调用，如果你dll的dll引用位置不对，也是会有一样的报错信息，所以通常需要确定dll本身没有其他的调用或者是确定他的其他dll的引用路径

**Comment by dev-kain** [comment]
> 是，dll之间会相互调用，如果你dll的dll引用位置不对，也是会有一样的报错信息，所以通常需要确定dll本身没有其他的调用或者是确定他的其他dll的引用路径

但是据我所知，我的c++代码里就一个 add 方法，你看我上面发的代码就知道了。。 就一个基础函数 return a + b；那种，应该不是你说的这个原因

**Comment by sky-rainy** [comment]
> 但是据我所知，我的c++代码里就一个 add 方法，你看我上面发的代码就知道了。。 就一个基础函数 return a + b；那种，应该不是你说的这个原因

你这种问题 加群 发截图吧，这里定位不到你得问题      群号12354891

**Comment by dev-kain** [comment]
> > 但是据我所知，我的c++代码里就一个 add 方法，你看我上面发的代码就知道了。。 就一个基础函数 return a + b；那种，应该不是你说的这个原因
> 
> 你这种问题 加群 发截图吧，这里定位不到你得问题 群号12354891

已加。

**Comment by dev-kain** [comment]
done；
问题定位：`process.env.libPath` 为 `undefined`
问题解决：通过直接引入 `src/main/config/staticPath` 内`libPath` 变量解决。
