### ISSUE TITLE
这个能打包成web吗

### ISSUE THREAD

**Issue by QiHong20** [umbrella22/electron-vue-template#95]

**Comment by QiHong20** [comment]
![image](https://user-images.githubusercontent.com/23076638/183650374-b3d5ca0c-b3db-49a4-bef7-cad043fedd9a.png)
yarn run build:web报了这个错。有大佬看看吗

**Comment by umbrella22** [comment]
如果要打包web的话需要手动移除所有electron引用，你如果有web平台需求请移步我的vite项目中的严格分支，很抱歉现在才回复
