### ISSUE TITLE
mac 开发环境和 打包环境 无法使用复制粘贴等功能

### ISSUE THREAD

**Issue by dark-kingA** [umbrella22/electron-vue-template#97]
mac 开发环境和 打包环境 无法使用复制粘贴等功能

**Comment by umbrella22** [comment]
复制粘贴功能需要自己显式添加快捷键哦~否则macos是不允许直接进行复制粘贴哒
[menu菜单](http://www.electronjs.org/zh/docs/latest/api/menu)
